spring.application.name=Schedule

api.security.token.secret=${JWT_SECRET:secret}

google.client.id=${GOOGLE_CLIENT_ID}

spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DATABASE_DRIVER:org.h2.Driver}
spring.datasource.username=${DATABASE_USER:sa}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.jpa.database-platform=${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${DATABASE_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

server.port=8081